# This is a basic workflow to help you get started with Actions
name: PullRequestCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.10]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Relative path
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: python3 -m pip install -r dev_env/pip3_requirements.txt
